// <auto-generated />
using ArtisoraServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtisoraServer.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ArtisoraServer.image", b =>
                {
                    b.Property<int>("imageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("imageId"), 1L, 1);

                    b.Property<string>("imageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("menteeId")
                        .HasColumnType("int");

                    b.Property<int>("mentorshipId")
                        .HasColumnType("int");

                    b.HasKey("imageId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("ArtisoraServer.login", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.HasKey("email");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("ArtisoraServer.mentee", b =>
                {
                    b.Property<int>("menteeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("menteeId"), 1L, 1);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("menteeId");

                    b.ToTable("Mentees");
                });

            modelBuilder.Entity("ArtisoraServer.mentor", b =>
                {
                    b.Property<int>("mentorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mentorId"), 1L, 1);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("mentorId");

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("ArtisoraServer.mentorship", b =>
                {
                    b.Property<int>("mentorshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mentorshipId"), 1L, 1);

                    b.Property<int>("menteeId")
                        .HasColumnType("int");

                    b.Property<int>("mentorId")
                        .HasColumnType("int");

                    b.HasKey("mentorshipId");

                    b.ToTable("Mentorships");
                });

            modelBuilder.Entity("ArtisoraServer.message", b =>
                {
                    b.Property<int>("messageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("messageId"), 1L, 1);

                    b.Property<int>("mentorshipId")
                        .HasColumnType("int");

                    b.Property<string>("textContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("messageId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ArtisoraServer.showcase", b =>
                {
                    b.Property<int>("showcaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("showcaseId"), 1L, 1);

                    b.Property<string>("image1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image1Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image2Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image3Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("mentorId")
                        .HasColumnType("int");

                    b.Property<string>("selfDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("showcaseId");

                    b.ToTable("Showcases");
                });
#pragma warning restore 612, 618
        }
    }
}
